# This is a basic workflow to help you get started with Actions

name: Test issue 6# & 7#

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
env:
  TZ: 'Asia/Shanghai'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:  

      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with: 
          node-version: '16'

      - name: npm install
        run: npm install

      - name: SFTP uploader
        uses: wangyucode/sftp-upload-action@v1.4.1
        with:
          host: '121.89.216.18'
          port: 5190
          privateKey: ${{ secrets.SERVER_KEY }} 
          localDir: './node_modules'
          remoteDir: '/root/test/blablabla'

      - name: Criando diretorio OK
        run: mkdir -p /home/runner/work/blablabla/ok

      - name: Criando arquivo .ok
        run: touch /home/runner/work/blablabla/ok/deploy.ok

      - name: SFTP uploader
        uses: wangyucode/sftp-upload-action@v1.4.1
        with:
          host: '121.89.216.18'
          port: 5190
          privateKey: ${{ secrets.SERVER_KEY }} 
          localDir: '/home/runner/work/blablabla/ok'
          remoteDir: '/root/test/blablabla'

