# This is a basic workflow to help you get started with Actions

name: Test action

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
env:
  TZ: 'Asia/Shanghai'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:  

      - name: create files
        run: |
          mkdir -p dist/.git
          echo "hello server1" > dist/1.txt
          echo "hello server2" > dist/2.tx
          echo "hello server3" > dist/3.t
          echo "hello server4" > dist/.git/4.txt

      - name: SFTP uploader
        uses: wangyucode/sftp-upload-action@v1.3.3
        with:
          host: 'wycode.cn'
          port: 22 # optional, default is 22 
          privateKey: ${{ secrets.SERVER_KEY }} 
          localDir: 'dist'
          remoteDir: '/root/test/'
          exclude: '1.txt,*.t,.git'
          excludeMode: 'ignore'
          dryRun: true # optional
          
          
